


notification:
  sms:
    enabled: true
    provider:
      authorization-header: Basic dGFuemltXzAwMDk1L21jbHNfaXRlOkM2b1ppQUdQSlFkQ0Q1TlU=
      uri: https://sms.magfa.com/api/http/sms/v2/send
    sender-number: 300097500059
  email:
    enabled: false
    provider:
      uri:

web:
  client:
    time-out:
      connection: 10000
      response: 10000