
# a random port number will be assigned for each instance of app:
server:
  port: 6767
#${PORT:0}

spring:
  application:
    name: notification-engine-ws

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      # the url by which the client apps communicate with Eureka server
      defaultZone: http://localhost:8010/eureka


#logging:
#  appender:
#    console:
#      enabled: false
#    file:
#      enabled: false
#    rabbit:
#      enabled: false
#      required: true
#      destination:
#        host: localhost
#        port: 5672
#        username: guest
#        password: guest
#        virtualHost: /
#        exchangeType: topic
#        exchangeName: logs
#    logstash:
#      enabled: true
#      destination:
#        url: localhost
#        port: 5044


#logging:
#  level:
#    com:
#      netflix:
#        discovery: OFF


notification:
  sms:
    enabled: true
    provider:
      authorization-header: Basic dGFuemltXzAwMDk1L21jbHNfaXRlOkM2b1ppQUdQSlFkQ0Q1TlU=
      uri: https://sms.magfa.com/api/http/sms/v2/send
    sender-number: 300097500059
  email:
    enabled: false
    provider:
      uri:

web:
  client:
    time-out:
      connection: 10000
      response: 10000