version: '3.8'

services:
  backoffice-webapi:
    build:
      context: ./backoffice/backoffice-webapi  # Path to the module with Dockerfile
    image: ${CI_REGISTRY}/backoffice-webapi:latest
    ports:
      - "9999:9999"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - database
    networks:
      - meysam-docker

#  another-module:
#    build:
#      context: ./another/module  # Path to the next module
#    image: another-module:latest
#    ports:
#      - "8081:8080" # Map to a different port as needed
##    environment:
##      - SPRING_PROFILES_ACTIVE=docker
##    depends_on:
##      - database
#    networks:
#      - meysam-docker

#  database:
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=youruser
#      - POSTGRES_PASSWORD=yourpassword
#      - POSTGRES_DB=yourdatabase
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:

networks:
  your-network-name:
    driver: bridge