version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - meysam-docker

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - meysam-docker

  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    restart: always
    command:
      - redis-server
    volumes:
      - ./redis_data:/data
    networks:
      - meysam-docker

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:


networks:
  meysam-docker:
    driver: bridge
