version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/data/pgadmin
    depends_on:
        - postgres
        
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
#    networks:
#      - test-network


  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:21.1.1
      environment:
       KEYCLOAK_ADMIN: admin
       KEYCLOAK_ADMIN_PASSWORD: password
       KC_PROXY: edge
       KC_HOSTNAME_STRICT: "false"
       KC_HTTP_ENABLED: "true"
       KC_DB: postgres
       KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
       KC_DB_USERNAME: admin
       KC_DB_PASSWORD: password
       JDBC_PARAMS: useSSL=false
      command: start
#      start-dev --features=preview
        #--hostname=localhost:8080 --auto-build --db:postgres --db-url=postgres --db-password=password --db-port=5432 --db-schema=public --http-enabled true --hostname-strict-https false
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - "8080:8080"
      restart: always
      depends_on:
        - postgres
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
volumes:
  postgres_data:
  pgadmin_data:
