version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - meysam-docker

volumes:
  postgres_data:

networks:
  meysam-docker:
    driver: bridge
