server:
  port: ${PROD_SERVER_PORT:9999}

spring:
  application:
    name: backoffice-ws
  profiles:
    active: native
  security:
    enabled: ${PROD_SPRING_SECURITY_ENABLED:true}
    ignored:
      paths: ${PROD_SPRING_SECURITY_IGNORED_PATHS:/swagger-ui/**,/public/**,/api/public/**}

  datasource:
    driverClassName: ${PROD_SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${PROD_SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    username: ${PROD_SPRING_DATASOURCE_USERNAME:admin}
    password: ${PROD_SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: ${PROD_SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${PROD_SPRING_JPA_SHOW_SQL:true}

  data:
    redis:
      host: ${PROD_SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${PROD_SPRING_DATA_REDIS_PORT:6379}
      password: ${PROD_SPRING_DATA_REDIS_PASSWORD:######}
      connect-timeout: ${PROD_SPRING_DATA_REDIS_CONNECT_TIMEOUT:10000}
      timeout: ${PROD_SPRING_DATA_REDIS_TIMEOUT:10000}
      jedis:
        pool:
          enabled: ${PROD_SPRING_DATA_REDIS_POOL_ENABLED:true}
          max-active: ${PROD_SPRING_DATA_REDIS_POOL_MAX_ACTIVE:300}
          max-wait: ${PROD_SPRING_DATA_REDIS_POOL_MAX_WAIT:5000}
          max-idle: ${PROD_SPRING_DATA_REDIS_POOL_MAX_IDLE:100}
          min-idle: ${PROD_SPRING_DATA_REDIS_POOL_MIN_IDLE:20}

  rabbitmq:
    host: ${PROD_SPRING_RABBITMQ_HOST:localhost}
    port: ${PROD_SPRING_RABBITMQ_PORT:5672}
    username: ${PROD_SPRING_RABBITMQ_USERNAME:guest}
    password: ${PROD_SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_DEFAULT_ZONE:http://localhost:8010/eureka}

oauth:
  client:
    secret: ${PROD_OAUTH_CLIENT_SECRET:rreJT7l3U5ZKIFVcqeeeEvzBB7a0tHWC}

jwt:
  secret: ${PROD_JWT_SECRET:GlCUaHlZfK0qLMKBNcpAvdOpHrDoCi7sN0WgSv3T9FKUlK7Ycxc2YQ0Ql1hdufHuXOUTsJrYHSwKkA1mDnF1TX0XTxR5IWAlAoUAK3Ncz9HYfzFl2dt6ikqplqlz88CTP00Ya}
  token:
    validity: ${PROD_JWT_TOKEN_VALIDITY:86400}


web:
  client:
    time-out:
      connection: 10000
      response: 10000

notification:
  sms:
    enabled: false
    provider:
      uri: https://sms
    sender-number: 3008264823
  email:
    enabled: false
    provider:
      uri:

outbox:
  processing:
    page:
      size: 100
  retry:
    count: 3
