# a random port number will be assigned for each instance of app:
server:
  port: 9999
#${PORT:0}

spring:
  application:
    name: backoffice-ws

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      # the url by which the client apps communicate with Eureka server
      defaultZone: http://localhost:8010/eureka

#logging:
#  appender:
#    console:
#      enabled: false
#    file:
#      enabled: false
#    rabbit:
#      enabled: false
#      required: true
#      destination:
#        host: localhost
#        port: 5672
#        username: guest
#        password: guest
#        virtualHost: /
#        exchangeType: topic
#        exchangeName: logs
#    logstash:
#      enabled: true
#      destination:
#        url: localhost
#        port: 5044

