# a random port number will be assigned for each instance of app:
server:
  port: 9999
#${PORT:0}

spring:
  application:
    name: backoffice-ws
  security:
    enabled: true
    ignored:
      paths: >
        /swagger-ui/**,
        /public/**,
        /api/public/**
  datasource:
    driverClassName: org.postgresql.Driver
    #    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      # the url by which the client apps communicate with Eureka server
      defaultZone: http://localhost:8010/eureka

is:
  test: false
oauth:
  client:
    secret: rreJT7l3U5ZKIFVcqeeeEvzBB7a0tHWC
api:
  checkToken:
    url: https://sso_service_base_path/check_token

jwt:
  secret: GlCUaHlZfK0qLMKBNcpAvdOpHrDoCi7sN0WgSv3T9FKUlK7Ycxc2YQ0Ql1hdufHuXOUTsJrYHSwKkA1mDnF1TX0XTxR5IWAlAoUAK3Ncz9HYfzFl2dt6ikqplqlz88CTP00Ya
  token:
    validity: 86400
#logging:
#  appender:
#    console:
#      enabled: false
#    file:
#      enabled: false
#    rabbit:
#      enabled: false
#      required: true
#      destination:
#        host: localhost
#        port: 5672
#        username: guest
#        password: guest
#        virtualHost: /
#        exchangeType: topic
#        exchangeName: logs
#    logstash:
#      enabled: true
#      destination:
#        url: localhost
#        port: 5044


#logging:
#  level:
#    root: INFO
#    com:
#      netflix:
#        discovery: OFF
