apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
    spring-boot: "true" #is set for Spring Boot Admin discovery purposes
spec:
  ports:
    - name: 8012-8012
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: config-server
  type: ClusterIP