#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: postgres
#  labels:
#    app: postgres
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: postgres
#  template:
#    metadata:
#      labels:
#        app: postgres
#    spec:
#      containers:
#        - name: postgres
#          image: postgres:14.2
#          ports:
#            - containerPort: 5432
#          volumeMounts:
#            - name: postgres
#              mountPath: /postgres_data # is this enough? shouldn't we map it to /var/lib/postgresql/data???
#      volumes:
#        - name: storage
#          persistentVolumeClaim:
#            claimName: postgres-pvc
#
#          env:
#            - name: POSTGRES_DB
#              value: keycloak #for initializing keycloak db on first start
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres
#                  key: postgres-user
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres
#                  key: postgres-password
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 256Mi
#
#
#
#
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#  labels:
#    app: postgres
#spec:
#  ports:
#    - port: 5432
#      targetPort: 5432
#      protocol: TCP
#  selector:
#    app: postgres
#
#    ## why service type isn't settled here?