apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  labels:
    app: backoffice

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice
  template:
    metadata:
      labels:
        app: backoffice
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: backoffice
          image: backoffice
          ports:
            - containerPort: 9999
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"